language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - node_module

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install --production=false --frozen-lockfile --non-interactive
  - yarn build:lib
