language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - node_module

install:
  - yarn install --production=false --frozen-lockfile --non-interactive
  - yarn build
  - yarn build:lib
